name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Orchestrator
        run: cd orchestrator && cargo build --all --verbose
      - name: Run Orchestrator tests
        run: cd orchestrator && cargo test --all --verbose
